// Code generated by go generate ./...; DO NOT EDIT.

package raylib

import "unsafe"

// Initialize audio device and context
func InitAudioDevice() {
	initAudioDevice.Void()
}

// Close the audio device and context
func CloseAudioDevice() {
	closeAudioDevice.Void()
}

// Check if audio device has been initialized successfully
func IsAudioDeviceReady() (res bool) {
	res = isAudioDeviceReady.Bool()
	return res
}

// Set master volume (listener)
func SetMasterVolume(volume float32) {
	a0 := float32(volume)
	setMasterVolume.Void(unsafe.Pointer(&a0))
}

// Get master volume (listener)
func GetMasterVolume() (res float32) {
	getMasterVolume.Call(unsafe.Pointer(&res))
	return res
}

// Load wave data from file
func LoadWave(fileName string) (res Wave) {
	a0 := tocstring(fileName)
	loadWave.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Load wave from memory buffer, fileType refers to extension: i.e. '.wav'
func LoadWaveFromMemory(fileType string, fileData string, dataSize int) (res Wave) {
	a0 := tocstring(fileType)
	a1 := tocstring(fileData)
	a2 := int64(dataSize)
	loadWaveFromMemory.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
	return res
}

// Checks if wave data is valid (data loaded and parameters)
func IsWaveValid(wave Wave) (res bool) {
	a0 := Wave(wave)
	res = isWaveValid.Bool(unsafe.Pointer(&a0))
	return res
}

// Load sound from file
func LoadSound(fileName string) (res Sound) {
	a0 := tocstring(fileName)
	loadSound.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Load sound from wave data
func LoadSoundFromWave(wave Wave) (res Sound) {
	a0 := Wave(wave)
	loadSoundFromWave.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Create a new sound that shares the same sample data as the source sound, does not own the sound data
func LoadSoundAlias(source Sound) (res Sound) {
	a0 := Sound(source)
	loadSoundAlias.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Checks if a sound is valid (data loaded and buffers initialized)
func IsSoundValid(sound Sound) (res bool) {
	a0 := Sound(sound)
	res = isSoundValid.Bool(unsafe.Pointer(&a0))
	return res
}

// Update sound buffer with new data
func UpdateSound(sound Sound, data unsafe.Pointer, sampleCount int) {
	a0 := Sound(sound)
	a1 := unsafe.Pointer(data)
	a2 := int64(sampleCount)
	updateSound.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
}

// Unload wave data
func UnloadWave(wave Wave) {
	a0 := Wave(wave)
	unloadWave.Void(unsafe.Pointer(&a0))
}

// Unload sound
func UnloadSound(sound Sound) {
	a0 := Sound(sound)
	unloadSound.Void(unsafe.Pointer(&a0))
}

// Unload a sound alias (does not deallocate sample data)
func UnloadSoundAlias(alias Sound) {
	a0 := Sound(alias)
	unloadSoundAlias.Void(unsafe.Pointer(&a0))
}

// Export wave data to file, returns true on success
func ExportWave(wave Wave, fileName string) (res bool) {
	a0 := Wave(wave)
	a1 := tocstring(fileName)
	res = exportWave.Bool(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Export wave sample data to code (.h), returns true on success
func ExportWaveAsCode(wave Wave, fileName string) (res bool) {
	a0 := Wave(wave)
	a1 := tocstring(fileName)
	res = exportWaveAsCode.Bool(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Play a sound
func PlaySound(sound Sound) {
	a0 := Sound(sound)
	playSound.Void(unsafe.Pointer(&a0))
}

// Stop playing a sound
func StopSound(sound Sound) {
	a0 := Sound(sound)
	stopSound.Void(unsafe.Pointer(&a0))
}

// Pause a sound
func PauseSound(sound Sound) {
	a0 := Sound(sound)
	pauseSound.Void(unsafe.Pointer(&a0))
}

// Resume a paused sound
func ResumeSound(sound Sound) {
	a0 := Sound(sound)
	resumeSound.Void(unsafe.Pointer(&a0))
}

// Check if a sound is currently playing
func IsSoundPlaying(sound Sound) (res bool) {
	a0 := Sound(sound)
	res = isSoundPlaying.Bool(unsafe.Pointer(&a0))
	return res
}

// Set volume for a sound (1.0 is max level)
func SetSoundVolume(sound Sound, volume float32) {
	a0 := Sound(sound)
	a1 := float32(volume)
	setSoundVolume.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Set pitch for a sound (1.0 is base level)
func SetSoundPitch(sound Sound, pitch float32) {
	a0 := Sound(sound)
	a1 := float32(pitch)
	setSoundPitch.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Set pan for a sound (0.5 is center)
func SetSoundPan(sound Sound, pan float32) {
	a0 := Sound(sound)
	a1 := float32(pan)
	setSoundPan.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Copy a wave to a new wave
func WaveCopy(wave Wave) (res Wave) {
	a0 := Wave(wave)
	waveCopy.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Crop a wave to defined frames range
func WaveCrop(wave *Wave, initFrame int, finalFrame int) {
	a0 := (*Wave)(wave)
	a1 := int64(initFrame)
	a2 := int64(finalFrame)
	waveCrop.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
}

// Convert wave data to desired format
func WaveFormat(wave *Wave, sampleRate int, sampleSize int, channels int) {
	a0 := (*Wave)(wave)
	a1 := int64(sampleRate)
	a2 := int64(sampleSize)
	a3 := int64(channels)
	waveFormat.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2), unsafe.Pointer(&a3))
}

// Load samples data from wave as a 32bit float data array
func LoadWaveSamples(wave Wave) (res *float32) {
	a0 := Wave(wave)
	loadWaveSamples.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Unload samples data loaded with LoadWaveSamples()
func UnloadWaveSamples(samples *float32) {
	a0 := (*float32)(samples)
	unloadWaveSamples.Void(unsafe.Pointer(&a0))
}
