// Code generated by go generate; DO NOT EDIT.

package raylib

import (
	"unsafe"

	"github.com/judah-caruso/raylib-purego/internal"
)

// Initialize audio device and context
func InitAudioDevice() {
	internal.InitAudioDevice.Void()
}

// Close the audio device and context
func CloseAudioDevice() {
	internal.CloseAudioDevice.Void()
}

// Check if audio device has been initialized successfully
func IsAudioDeviceReady() (res bool) {
	res = internal.IsAudioDeviceReady.Bool()
	return res
}

// Set master volume (listener)
func SetMasterVolume(volume float32) {
	a0 := float32(volume)
	internal.SetMasterVolume.Void(unsafe.Pointer(&a0))
}

// Get master volume (listener)
func GetMasterVolume() (res float32) {
	internal.GetMasterVolume.Call(unsafe.Pointer(&res))
	return res
}

// Load wave data from file
func LoadWave(fileName string) (res Wave) {
	a0 := tocstring(fileName)
	internal.LoadWave.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Load wave from memory buffer, fileType refers to extension: i.e. '.wav'
func LoadWaveFromMemory(fileType string, fileData string, dataSize int) (res Wave) {
	a0 := tocstring(fileType)
	a1 := tocstring(fileData)
	a2 := int64(dataSize)
	internal.LoadWaveFromMemory.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
	return res
}

// Checks if wave data is valid (data loaded and parameters)
func IsWaveValid(wave Wave) (res bool) {
	a0 := Wave(wave)
	res = internal.IsWaveValid.Bool(unsafe.Pointer(&a0))
	return res
}

// Load sound from file
func LoadSound(fileName string) (res Sound) {
	a0 := tocstring(fileName)
	internal.LoadSound.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Load sound from wave data
func LoadSoundFromWave(wave Wave) (res Sound) {
	a0 := Wave(wave)
	internal.LoadSoundFromWave.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Create a new sound that shares the same sample data as the source sound, does not own the sound data
func LoadSoundAlias(source Sound) (res Sound) {
	a0 := Sound(source)
	internal.LoadSoundAlias.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Checks if a sound is valid (data loaded and buffers initialized)
func IsSoundValid(sound Sound) (res bool) {
	a0 := Sound(sound)
	res = internal.IsSoundValid.Bool(unsafe.Pointer(&a0))
	return res
}

// Update sound buffer with new data
func UpdateSound(sound Sound, data unsafe.Pointer, sampleCount int) {
	a0 := Sound(sound)
	a1 := unsafe.Pointer(data)
	a2 := int64(sampleCount)
	internal.UpdateSound.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
}

// Unload wave data
func UnloadWave(wave Wave) {
	a0 := Wave(wave)
	internal.UnloadWave.Void(unsafe.Pointer(&a0))
}

// Unload sound
func UnloadSound(sound Sound) {
	a0 := Sound(sound)
	internal.UnloadSound.Void(unsafe.Pointer(&a0))
}

// Unload a sound alias (does not deallocate sample data)
func UnloadSoundAlias(alias Sound) {
	a0 := Sound(alias)
	internal.UnloadSoundAlias.Void(unsafe.Pointer(&a0))
}

// Export wave data to file, returns true on success
func ExportWave(wave Wave, fileName string) (res bool) {
	a0 := Wave(wave)
	a1 := tocstring(fileName)
	res = internal.ExportWave.Bool(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Export wave sample data to code (.h), returns true on success
func ExportWaveAsCode(wave Wave, fileName string) (res bool) {
	a0 := Wave(wave)
	a1 := tocstring(fileName)
	res = internal.ExportWaveAsCode.Bool(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Play a sound
func PlaySound(sound Sound) {
	a0 := Sound(sound)
	internal.PlaySound.Void(unsafe.Pointer(&a0))
}

// Stop playing a sound
func StopSound(sound Sound) {
	a0 := Sound(sound)
	internal.StopSound.Void(unsafe.Pointer(&a0))
}

// Pause a sound
func PauseSound(sound Sound) {
	a0 := Sound(sound)
	internal.PauseSound.Void(unsafe.Pointer(&a0))
}

// Resume a paused sound
func ResumeSound(sound Sound) {
	a0 := Sound(sound)
	internal.ResumeSound.Void(unsafe.Pointer(&a0))
}

// Check if a sound is currently playing
func IsSoundPlaying(sound Sound) (res bool) {
	a0 := Sound(sound)
	res = internal.IsSoundPlaying.Bool(unsafe.Pointer(&a0))
	return res
}

// Set volume for a sound (1.0 is max level)
func SetSoundVolume(sound Sound, volume float32) {
	a0 := Sound(sound)
	a1 := float32(volume)
	internal.SetSoundVolume.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Set pitch for a sound (1.0 is base level)
func SetSoundPitch(sound Sound, pitch float32) {
	a0 := Sound(sound)
	a1 := float32(pitch)
	internal.SetSoundPitch.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Set pan for a sound (0.5 is center)
func SetSoundPan(sound Sound, pan float32) {
	a0 := Sound(sound)
	a1 := float32(pan)
	internal.SetSoundPan.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Copy a wave to a new wave
func WaveCopy(wave Wave) (res Wave) {
	a0 := Wave(wave)
	internal.WaveCopy.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Crop a wave to defined frames range
func WaveCrop(wave *Wave, initFrame int, finalFrame int) {
	a0 := (*Wave)(wave)
	a1 := int64(initFrame)
	a2 := int64(finalFrame)
	internal.WaveCrop.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
}

// Convert wave data to desired format
func WaveFormat(wave *Wave, sampleRate int, sampleSize int, channels int) {
	a0 := (*Wave)(wave)
	a1 := int64(sampleRate)
	a2 := int64(sampleSize)
	a3 := int64(channels)
	internal.WaveFormat.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2), unsafe.Pointer(&a3))
}

// Load samples data from wave as a 32bit float data array
func LoadWaveSamples(wave Wave) (res *float32) {
	a0 := Wave(wave)
	internal.LoadWaveSamples.Call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Unload samples data loaded with LoadWaveSamples()
func UnloadWaveSamples(samples *float32) {
	a0 := (*float32)(samples)
	internal.UnloadWaveSamples.Void(unsafe.Pointer(&a0))
}
