// Code generated by go generate ./...; DO NOT EDIT.

package raylib

import "unsafe"

// Initialize window and OpenGL context
func InitWindow(width int, height int, title string) {
	a0 := int64(width)
	a1 := int64(height)
	a2 := tocstring(title)
	initWindow.void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
}

// Close window and unload OpenGL context
func CloseWindow() {
	closeWindow.void()
}

// Check if application should close (KEY_ESCAPE pressed or windows close icon clicked)
func WindowShouldClose() (res bool) {
	res = windowShouldClose.bool()
	return res
}

// Check if window has been initialized successfully
func IsWindowReady() (res bool) {
	res = isWindowReady.bool()
	return res
}

// Check if window is currently fullscreen
func IsWindowFullscreen() (res bool) {
	res = isWindowFullscreen.bool()
	return res
}

// Check if window is currently hidden
func IsWindowHidden() (res bool) {
	res = isWindowHidden.bool()
	return res
}

// Check if window is currently minimized
func IsWindowMinimized() (res bool) {
	res = isWindowMinimized.bool()
	return res
}

// Check if window is currently maximized
func IsWindowMaximized() (res bool) {
	res = isWindowMaximized.bool()
	return res
}

// Check if window is currently focused
func IsWindowFocused() (res bool) {
	res = isWindowFocused.bool()
	return res
}

// Check if window has been resized last frame
func IsWindowResized() (res bool) {
	res = isWindowResized.bool()
	return res
}

// Check if one specific window flag is enabled
func IsWindowState(flag ConfigFlags) (res bool) {
	a0 := ConfigFlags(flag)
	res = isWindowState.bool(unsafe.Pointer(&a0))
	return res
}

// Set window configuration state using flags
func SetWindowState(flags ConfigFlags) {
	a0 := ConfigFlags(flags)
	setWindowState.void(unsafe.Pointer(&a0))
}

// Clear window configuration state flags
func ClearWindowState(flags ConfigFlags) {
	a0 := ConfigFlags(flags)
	clearWindowState.void(unsafe.Pointer(&a0))
}

// Toggle window state: fullscreen/windowed, resizes monitor to match window resolution
func ToggleFullscreen() {
	toggleFullscreen.void()
}

// Toggle window state: borderless windowed, resizes window to match monitor resolution
func ToggleBorderlessWindowed() {
	toggleBorderlessWindowed.void()
}

// Set window state: maximized, if resizable
func MaximizeWindow() {
	maximizeWindow.void()
}

// Set window state: minimized, if resizable
func MinimizeWindow() {
	minimizeWindow.void()
}

// Set window state: not minimized/maximized
func RestoreWindow() {
	restoreWindow.void()
}

// Set icon for window (single image, RGBA 32bit)
func SetWindowIcon(image Image) {
	a0 := Image(image)
	setWindowIcon.void(unsafe.Pointer(&a0))
}

// Set icon for window (multiple images, RGBA 32bit)
func SetWindowIcons(images *Image, count int) {
	a0 := (*Image)(images)
	a1 := int64(count)
	setWindowIcons.void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Set title for window
func SetWindowTitle(title string) {
	a0 := tocstring(title)
	setWindowTitle.void(unsafe.Pointer(&a0))
}

// Set window position on screen
func SetWindowPosition(x int, y int) {
	a0 := int64(x)
	a1 := int64(y)
	setWindowPosition.void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Set monitor for the current window
func SetWindowMonitor(monitor int) {
	a0 := int64(monitor)
	setWindowMonitor.void(unsafe.Pointer(&a0))
}

// Set window minimum dimensions (for FLAG_WINDOW_RESIZABLE)
func SetWindowMinSize(width int, height int) {
	a0 := int64(width)
	a1 := int64(height)
	setWindowMinSize.void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Set window maximum dimensions (for FLAG_WINDOW_RESIZABLE)
func SetWindowMaxSize(width int, height int) {
	a0 := int64(width)
	a1 := int64(height)
	setWindowMaxSize.void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Set window dimensions
func SetWindowSize(width int, height int) {
	a0 := int64(width)
	a1 := int64(height)
	setWindowSize.void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Set window opacity [0.0f..1.0f]
func SetWindowOpacity(opacity float32) {
	a0 := float32(opacity)
	setWindowOpacity.void(unsafe.Pointer(&a0))
}

// Set window focused
func SetWindowFocused() {
	setWindowFocused.void()
}

// Get native window handle
func GetWindowHandle() (res unsafe.Pointer) {
	getWindowHandle.call(unsafe.Pointer(&res))
	return res
}

// Get current screen width
func GetScreenWidth() (res int32) {
	res = getScreenWidth.int32()
	return res
}

// Get current screen height
func GetScreenHeight() (res int32) {
	res = getScreenHeight.int32()
	return res
}

// Get current render width (it considers HiDPI)
func GetRenderWidth() (res int32) {
	res = getRenderWidth.int32()
	return res
}

// Get current render height (it considers HiDPI)
func GetRenderHeight() (res int32) {
	res = getRenderHeight.int32()
	return res
}

// Get number of connected monitors
func GetMonitorCount() (res int32) {
	res = getMonitorCount.int32()
	return res
}

// Get current monitor where window is placed
func GetCurrentMonitor() (res int32) {
	res = getCurrentMonitor.int32()
	return res
}

// Get specified monitor position
func GetMonitorPosition(monitor int) (res Vector2) {
	a0 := int64(monitor)
	getMonitorPosition.call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Get specified monitor width (current video mode used by monitor)
func GetMonitorWidth(monitor int) (res int32) {
	a0 := int64(monitor)
	res = getMonitorWidth.int32(unsafe.Pointer(&a0))
	return res
}

// Get specified monitor height (current video mode used by monitor)
func GetMonitorHeight(monitor int) (res int32) {
	a0 := int64(monitor)
	res = getMonitorHeight.int32(unsafe.Pointer(&a0))
	return res
}

// Get specified monitor physical width in millimetres
func GetMonitorPhysicalWidth(monitor int) (res int32) {
	a0 := int64(monitor)
	res = getMonitorPhysicalWidth.int32(unsafe.Pointer(&a0))
	return res
}

// Get specified monitor physical height in millimetres
func GetMonitorPhysicalHeight(monitor int) (res int32) {
	a0 := int64(monitor)
	res = getMonitorPhysicalHeight.int32(unsafe.Pointer(&a0))
	return res
}

// Get specified monitor refresh rate
func GetMonitorRefreshRate(monitor int) (res int32) {
	a0 := int64(monitor)
	res = getMonitorRefreshRate.int32(unsafe.Pointer(&a0))
	return res
}

// Get window position XY on monitor
func GetWindowPosition() (res Vector2) {
	getWindowPosition.call(unsafe.Pointer(&res))
	return res
}

// Get window scale DPI factor
func GetWindowScaleDPI() (res Vector2) {
	getWindowScaleDPI.call(unsafe.Pointer(&res))
	return res
}

// Get the human-readable, UTF-8 encoded name of the specified monitor
func GetMonitorName(monitor int) (res *byte) {
	a0 := int64(monitor)
	getMonitorName.call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Set clipboard text content
func SetClipboardText(text string) {
	a0 := tocstring(text)
	setClipboardText.void(unsafe.Pointer(&a0))
}

// Get clipboard text content
func GetClipboardText() (res *byte) {
	getClipboardText.call(unsafe.Pointer(&res))
	return res
}

// Get clipboard image
func GetClipboardImage() (res Image) {
	getClipboardImage.call(unsafe.Pointer(&res))
	return res
}

// Enable waiting for events on EndDrawing(), no automatic event polling
func EnableEventWaiting() {
	enableEventWaiting.void()
}

// Disable waiting for events on EndDrawing(), automatic events polling
func DisableEventWaiting() {
	disableEventWaiting.void()
}

// Shows cursor
func ShowCursor() {
	showCursor.void()
}

// Hides cursor
func HideCursor() {
	hideCursor.void()
}

// Check if cursor is not visible
func IsCursorHidden() (res bool) {
	res = isCursorHidden.bool()
	return res
}

// Enables cursor (unlock cursor)
func EnableCursor() {
	enableCursor.void()
}

// Disables cursor (lock cursor)
func DisableCursor() {
	disableCursor.void()
}

// Check if cursor is on the screen
func IsCursorOnScreen() (res bool) {
	res = isCursorOnScreen.bool()
	return res
}

// Set background color (framebuffer clear color)
func ClearBackground(color Color) {
	a0 := Color(color)
	clearBackground.void(unsafe.Pointer(&a0))
}

// Setup canvas (framebuffer) to start drawing
func BeginDrawing() {
	beginDrawing.void()
}

// End canvas drawing and swap buffers (double buffering)
func EndDrawing() {
	endDrawing.void()
}

// Begin 2D mode with custom camera (2D)
func BeginMode2D(camera Camera2D) {
	a0 := Camera2D(camera)
	beginMode2D.void(unsafe.Pointer(&a0))
}

// Ends 2D mode with custom camera
func EndMode2D() {
	endMode2D.void()
}

// Begin 3D mode with custom camera (3D)
func BeginMode3D(camera Camera3D) {
	a0 := Camera3D(camera)
	beginMode3D.void(unsafe.Pointer(&a0))
}

// Ends 3D mode and returns to default 2D orthographic mode
func EndMode3D() {
	endMode3D.void()
}

// Begin drawing to render texture
func BeginTextureMode(target RenderTexture2D) {
	a0 := RenderTexture2D(target)
	beginTextureMode.void(unsafe.Pointer(&a0))
}

// Ends drawing to render texture
func EndTextureMode() {
	endTextureMode.void()
}

// Begin custom shader drawing
func BeginShaderMode(shader Shader) {
	a0 := Shader(shader)
	beginShaderMode.void(unsafe.Pointer(&a0))
}

// End custom shader drawing (use default shader)
func EndShaderMode() {
	endShaderMode.void()
}

// Begin blending mode (alpha, additive, multiplied, subtract, custom)
func BeginBlendMode(mode int) {
	a0 := int64(mode)
	beginBlendMode.void(unsafe.Pointer(&a0))
}

// End blending mode (reset to default: alpha blending)
func EndBlendMode() {
	endBlendMode.void()
}

// Begin scissor mode (define screen area for following drawing)
func BeginScissorMode(x int, y int, width int, height int) {
	a0 := int64(x)
	a1 := int64(y)
	a2 := int64(width)
	a3 := int64(height)
	beginScissorMode.void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2), unsafe.Pointer(&a3))
}

// End scissor mode
func EndScissorMode() {
	endScissorMode.void()
}

// Begin stereo rendering (requires VR simulator)
func BeginVrStereoMode(config VrStereoConfig) {
	a0 := VrStereoConfig(config)
	beginVrStereoMode.void(unsafe.Pointer(&a0))
}

// End stereo rendering (requires VR simulator)
func EndVrStereoMode() {
	endVrStereoMode.void()
}

// Load VR stereo config for VR simulator device parameters
func LoadVrStereoConfig(device VrDeviceInfo) (res VrStereoConfig) {
	a0 := VrDeviceInfo(device)
	loadVrStereoConfig.call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Unload VR stereo config
func UnloadVrStereoConfig(config VrStereoConfig) {
	a0 := VrStereoConfig(config)
	unloadVrStereoConfig.void(unsafe.Pointer(&a0))
}

// Load shader from files and bind default locations
func LoadShader(vsFileName string, fsFileName string) (res Shader) {
	a0 := tocstring(vsFileName)
	a1 := tocstring(fsFileName)
	loadShader.call(unsafe.Pointer(&res), unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Load shader from code strings and bind default locations
func LoadShaderFromMemory(vsCode string, fsCode string) (res Shader) {
	a0 := tocstring(vsCode)
	a1 := tocstring(fsCode)
	loadShaderFromMemory.call(unsafe.Pointer(&res), unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Check if a shader is valid (loaded on GPU)
func IsShaderValid(shader Shader) (res bool) {
	a0 := Shader(shader)
	res = isShaderValid.bool(unsafe.Pointer(&a0))
	return res
}

// Get shader uniform location
func GetShaderLocation(shader Shader, uniformName string) (res int32) {
	a0 := Shader(shader)
	a1 := tocstring(uniformName)
	res = getShaderLocation.int32(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Get shader attribute location
func GetShaderLocationAttrib(shader Shader, attribName string) (res int32) {
	a0 := Shader(shader)
	a1 := tocstring(attribName)
	res = getShaderLocationAttrib.int32(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Set shader uniform value
func SetShaderValue(shader Shader, locIndex int, value unsafe.Pointer, uniformType int) {
	a0 := Shader(shader)
	a1 := int64(locIndex)
	a2 := unsafe.Pointer(value)
	a3 := int64(uniformType)
	setShaderValue.void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2), unsafe.Pointer(&a3))
}

// Set shader uniform value vector
func SetShaderValueV(shader Shader, locIndex int, value unsafe.Pointer, uniformType int, count int) {
	a0 := Shader(shader)
	a1 := int64(locIndex)
	a2 := unsafe.Pointer(value)
	a3 := int64(uniformType)
	a4 := int64(count)
	setShaderValueV.void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2), unsafe.Pointer(&a3), unsafe.Pointer(&a4))
}

// Set shader uniform value (matrix 4x4)
func SetShaderValueMatrix(shader Shader, locIndex int, mat Matrix) {
	a0 := Shader(shader)
	a1 := int64(locIndex)
	a2 := Matrix(mat)
	setShaderValueMatrix.void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
}

// Set shader uniform value for texture (sampler2d)
func SetShaderValueTexture(shader Shader, locIndex int, texture Texture2D) {
	a0 := Shader(shader)
	a1 := int64(locIndex)
	a2 := Texture2D(texture)
	setShaderValueTexture.void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
}

// Unload shader from GPU memory (VRAM)
func UnloadShader(shader Shader) {
	a0 := Shader(shader)
	unloadShader.void(unsafe.Pointer(&a0))
}

// Get a ray trace from screen position (i.e mouse)
func GetScreenToWorldRay(position Vector2, camera Camera) (res Ray) {
	a0 := Vector2(position)
	a1 := Camera(camera)
	getScreenToWorldRay.call(unsafe.Pointer(&res), unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Get a ray trace from screen position (i.e mouse) in a viewport
func GetScreenToWorldRayEx(position Vector2, camera Camera, width int, height int) (res Ray) {
	a0 := Vector2(position)
	a1 := Camera(camera)
	a2 := int64(width)
	a3 := int64(height)
	getScreenToWorldRayEx.call(unsafe.Pointer(&res), unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2), unsafe.Pointer(&a3))
	return res
}

// Get the screen space position for a 3d world space position
func GetWorldToScreen(position Vector3, camera Camera) (res Vector2) {
	a0 := Vector3(position)
	a1 := Camera(camera)
	getWorldToScreen.call(unsafe.Pointer(&res), unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Get size position for a 3d world space position
func GetWorldToScreenEx(position Vector3, camera Camera, width int, height int) (res Vector2) {
	a0 := Vector3(position)
	a1 := Camera(camera)
	a2 := int64(width)
	a3 := int64(height)
	getWorldToScreenEx.call(unsafe.Pointer(&res), unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2), unsafe.Pointer(&a3))
	return res
}

// Get the screen space position for a 2d camera world space position
func GetWorldToScreen2D(position Vector2, camera Camera2D) (res Vector2) {
	a0 := Vector2(position)
	a1 := Camera2D(camera)
	getWorldToScreen2D.call(unsafe.Pointer(&res), unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Get the world space position for a 2d camera screen space position
func GetScreenToWorld2D(position Vector2, camera Camera2D) (res Vector2) {
	a0 := Vector2(position)
	a1 := Camera2D(camera)
	getScreenToWorld2D.call(unsafe.Pointer(&res), unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Get camera transform matrix (view matrix)
func GetCameraMatrix(camera Camera) (res Matrix) {
	a0 := Camera(camera)
	getCameraMatrix.call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Get camera 2d transform matrix
func GetCameraMatrix2D(camera Camera2D) (res Matrix) {
	a0 := Camera2D(camera)
	getCameraMatrix2D.call(unsafe.Pointer(&res), unsafe.Pointer(&a0))
	return res
}

// Set target FPS (maximum)
func SetTargetFPS(fps int) {
	a0 := int64(fps)
	setTargetFPS.void(unsafe.Pointer(&a0))
}

// Get time in seconds for last frame drawn (delta time)
func GetFrameTime() (res float32) {
	getFrameTime.call(unsafe.Pointer(&res))
	return res
}

// Get elapsed time in seconds since InitWindow()
func GetTime() (res float64) {
	getTime.call(unsafe.Pointer(&res))
	return res
}

// Get current FPS
func GetFPS() (res int32) {
	res = getFPS.int32()
	return res
}

// Swap back buffer with front buffer (screen drawing)
func SwapScreenBuffer() {
	swapScreenBuffer.void()
}

// Register all input events
func PollInputEvents() {
	pollInputEvents.void()
}

// Wait for some time (halt program execution)
func WaitTime(seconds float64) {
	a0 := float64(seconds)
	waitTime.void(unsafe.Pointer(&a0))
}

// Set the seed for the random number generator
func SetRandomSeed(seed uint) {
	a0 := uint64(seed)
	setRandomSeed.void(unsafe.Pointer(&a0))
}

// Get a random value between min and max (both included)
func GetRandomValue(min int, max int) (res int32) {
	a0 := int64(min)
	a1 := int64(max)
	res = getRandomValue.int32(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
	return res
}

// Load random values sequence, no values repeated
func LoadRandomSequence(count uint, min int, max int) (res int32) {
	a0 := uint64(count)
	a1 := int64(min)
	a2 := int64(max)
	res = loadRandomSequence.int32(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
	return res
}

// Unload random values sequence
func UnloadRandomSequence(sequence unsafe.Pointer) {
	a0 := unsafe.Pointer(sequence)
	unloadRandomSequence.void(unsafe.Pointer(&a0))
}

// Takes a screenshot of current screen (filename extension defines format)
func TakeScreenshot(fileName string) {
	a0 := tocstring(fileName)
	takeScreenshot.void(unsafe.Pointer(&a0))
}

// Setup init configuration flags (view FLAGS)
func SetConfigFlags(flags ConfigFlags) {
	a0 := ConfigFlags(flags)
	setConfigFlags.void(unsafe.Pointer(&a0))
}

// Open URL with default system browser (if available)
func OpenURL(url string) {
	a0 := tocstring(url)
	openURL.void(unsafe.Pointer(&a0))
}
