// Code generated by go generate; DO NOT EDIT.

package raylib

import (
	"unsafe"

	"github.com/judah-caruso/raylib-purego/internal"
)

// Draw a line in 3D world space
func DrawLine3D(startPos Vector3, endPos Vector3, color Color) {
	a0 := Vector3(startPos)
	a1 := Vector3(endPos)
	a2 := Color(color)
	internal.DrawLine3D.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
}

// Draw a point in 3D space, actually a small line
func DrawPoint3D(position Vector3, color Color) {
	a0 := Vector3(position)
	a1 := Color(color)
	internal.DrawPoint3D.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}

// Draw a grid (centered at (0, 0, 0))
func DrawGrid(slices int, spacing float32) {
	a0 := int64(slices)
	a1 := float32(spacing)
	internal.DrawGrid.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}
