// Code generated by go generate ./...; DO NOT EDIT.

package raylib

import "unsafe"

// Draw a line in 3D world space
func DrawLine3D(startPos Vector3, endPos Vector3, color Color) {
	a0 := Vector3(startPos)
	a1 := Vector3(endPos)
	a2 := Color(color)
	drawLine3D.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1), unsafe.Pointer(&a2))
}

// Draw a point in 3D space, actually a small line
func DrawPoint3D(position Vector3, color Color) {
	a0 := Vector3(position)
	a1 := Color(color)
	drawPoint3D.Void(unsafe.Pointer(&a0), unsafe.Pointer(&a1))
}
